"""first commit

Revision ID: 414e17599317
Revises: 
Create Date: 2023-09-14 11:10:39.112545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414e17599317'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Data Set 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Data Set 1',
    sa.Column('Item1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Item2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Item3', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
