"""second commit

Revision ID: 91280ca4dbee
Revises: 414e17599317
Create Date: 2023-09-14 11:25:13.279611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91280ca4dbee'
down_revision = '414e17599317'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
